# Generated by Django 6.0.5 on 2026-05-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_type', models.CharField(choices=[('SHS', 'Senior High School'), ('STEM', 'STEM School'), ('BOTH', 'Both')], default='SHS', max_length=4)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(default='🎯', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(help_text='Comma-separated keywords for NLP matching')),
                ('why_text', models.TextField(blank=True, help_text='Explanation shown to student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.learningarea')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('A', 'Core'), ('B', 'Learning Area Elective'), ('C', 'Related Learning Area Elective'), ('D', 'Other Elective')], max_length=1)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_externally_examinable', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('learning_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='careers.learningarea')),
            ],
        ),
        migrations.CreateModel(
            name='CareerRecommendationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_reasons', to='careers.career')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.subject')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='core_subjects',
            field=models.ManyToManyField(blank=True, related_name='career_core', to='careers.subject'),
        ),
        migrations.AddField(
            model_name='career',
            name='mandatory_electives',
            field=models.ManyToManyField(blank=True, related_name='career_mandatory', to='careers.subject'),
        ),
        migrations.AddField(
            model_name='career',
            name='recommended_electives',
            field=models.ManyToManyField(blank=True, related_name='career_recommended', to='careers.subject'),
        ),
    ]
