# Generated by Django 6.0.5 on 2026-06-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='icon',
            field=models.CharField(default='🎯', max_length=50),
        ),
    ]
