# Generated by Django 6.0.5 on 2026-06-24 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_career_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='learning_area',
        ),
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'Core'), ('B', 'Learning Area Elective'), ('C', 'Related Learning Area Elective'), ('D', 'Other Elective')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='SubjectLearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A', 'Core'), ('B', 'Learning Area Elective'), ('C', 'Related Learning Area Elective'), ('D', 'Other Elective')], max_length=1)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_learning_areas', to='careers.learningarea')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_learning_areas', to='careers.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='learning_areas',
            field=models.ManyToManyField(blank=True, related_name='subjects', through='careers.SubjectLearningArea', to='careers.learningarea'),
        ),
    ]
