# Generated by Django 6.0.5 on 2026-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_remove_subject_learning_area_alter_subject_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_mandatory',
        ),
        migrations.AddField(
            model_name='subjectlearningarea',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
