# Real programme + cut-off data extracted from official university admission PDFs
# (KNUST, UCC, UDS, UENR, UG). Cut-offs are the lowest aggregate = most competitive.
# Where a source gave a range or gender/category split, the number shown is the
# most representative single figure and a `note` is included with the detail.

PROGRAMS_BY_UNI = {

    "KNUST": {
        "Agriculture & Natural Resources": [
            ("BSc. Agriculture", 20),
            ("BSc. Agricultural Biotechnology", 17),
            ("BSc. Agribusiness Management", 15),
            ("BSc. Landscape Design and Management", 17),
            ("BSc. Natural Resources Management", 18),
            ("BSc. Forest Resources Technology", 24),
            ("BSc. Aquaculture and Water Resources Management", 20),
            ("BSc. Packaging Technology", 15),
        ],
        "Art & Built Environment": [
            ("BSc. Architecture", 7),
            ("BSc. Construction Technology and Management", 9),
            ("BSc. Quantity Surveying and Construction Economics", 9),
            ("BSc. Development Planning", 9),
            ("BSc. Human Settlement Planning", 10),
            ("BSc. Land Economy", 8),
            ("BSc. Real Estate", 9),
            ("BFA. Fine Art and Curatorial Practice", 16),
            ("BA. Communication Design (Graphic Design)", 11),
            ("BA. Integrated Rural Art and Industry", 15),
            ("BA. Publishing Studies", 12),
            ("BSc. Metal Product Design Technology", 16),
            ("BSc. Textile Design and Technology", 13),
            ("BSc. Fashion Design", 11),
            ("BSc. Ceramics Technology", 23),
            ("B.Ed. Junior High School Specialism", 15),
        ],
        "Engineering": [
            ("BSc. Aerospace Engineering", 7),
            ("BSc. Agricultural Engineering", 13),
            ("BSc. Automobile Engineering", 10),
            ("BSc. Biomedical Engineering", 6),
            ("BSc. Chemical Engineering", 7),
            ("BSc. Civil Engineering", 7),
            ("BSc. Computer Engineering", 6),
            ("BSc. Electrical/Electronic Engineering", 6),
            ("BSc. Geological Engineering", 8),
            ("BSc. Geomatic (Geodetic) Engineering", 9),
            ("BSc. Industrial Engineering", 10),
            ("BSc. Marine Engineering", 9),
            ("BSc. Materials Engineering", 10),
            ("BSc. Mechanical Engineering", 7),
            ("BSc. Metallurgical Engineering", 11),
            ("BSc. Petrochemical Engineering", 7),
            ("BSc. Petroleum Engineering", 6),
            ("BSc. Telecommunication Engineering", 9),
        ],
        "Health Sciences": [
            ("Bachelor of Dental Surgery (BDS)", 6),
            ("Doctor of Veterinary Medicine (DVM)", 10),
            ("BSc. Disability and Rehabilitation Studies", 13),
            ("Bachelor of Herbal Medicine (BHM)", 14),
            ("BSc. Human Biology (Medicine/MBChB)", 6),
            ("BSc. Medical Laboratory Science", 7),
            ("BSc. Medical Imaging", 7),
            ("BSc. Midwifery", 8),
            ("BSc. Nursing", 7),
            ("BSc. Physiotherapy and Sports Science", 12),
            ("Doctor of Pharmacy (Pharm D)", 6),
        ],
        "Humanities & Social Sciences": [
            ("BA. Akan Language and Culture", 22),
            ("BA. Economics", 10),
            ("BA. English", 13),
            ("BA. French and Francophone Studies", 14),
            ("BA. Geography and Rural Development", 10),
            ("BA. History", 15),
            ("BA. Linguistics", 15),
            ("BA. Media and Communication Studies", 9),
            ("BA. Political Studies", 9),
            ("Bachelor of Public Administration", 11),
            ("BA. Religion and Human Development", 20),
            ("BA. Sociology", 11),
            ("BA. Social Work", 11),
            ("BSc. Business Administration (HRM/Management)", 7),
            ("BSc. Business Administration (Marketing/Int'l Business)", 9),
            ("BSc. Business Administration (Accounting/Banking & Finance)", 7),
            ("BSc. Business Administration (Logistics/Supply Chain/Bus. IT)", 8),
            ("BSc. Hospitality and Tourism Management", 10),
            ("Bachelor of Laws (LLB)", 6),
        ],
        "Science": [
            ("BSc. Biochemistry", 9),
            ("BSc. Food Science and Technology", 11),
            ("BSc. Dietetics", 9),
            ("BSc. Human Nutrition", 10),
            ("BSc. Biological Science", 9),
            ("BSc. Environmental Science", 12),
            ("BSc. Chemistry", 15),
            ("BSc. Computer Science", 7),
            ("BSc. Information Technology", 10),
            ("BSc. Mathematics", 15),
            ("BSc. Actuarial Science", 10),
            ("BSc. Statistics", 12),
            ("BSc. Physics", 16),
            ("BSc. Meteorology and Climate Science", 17),
            ("Doctor of Optometry", 6),
        ],
    },

    "UCC": {
        "Arts": [
            ("Bachelor of Arts", 22),
            ("Bachelor of Arts (African Studies)", 19),
            ("Bachelor of Arts (Anthropology)", 22),
            ("Bachelor of Arts (Chinese)", 25),
            ("Bachelor of Arts (Communication Studies)", 17),
            ("Bachelor of Arts (Film Studies)", 25),
            ("Bachelor of Arts (Information Science)", 22),
            ("Bachelor of Arts (Linguistics)", 20),
            ("Bachelor of Arts (Population and Health)", 20),
            ("Bachelor of Arts (Social Sciences)", 20),
            ("Bachelor of Arts (Theatre Studies)", 23),
            ("Bachelor of Fine Art Education (Painting and Sculpture)", 19),
            ("Bachelor of Music", 21),
        ],
        "Business (Bachelor of Commerce)": [
            ("Bachelor of Commerce (Accounting)", 15),
            ("Bachelor of Commerce (Entrepreneurship with Graphic Design)", 18),
            ("Bachelor of Commerce (Finance)", 16),
            ("Bachelor of Commerce (Human Resource Management)", 17),
            ("Bachelor of Commerce (Management)", 22),
            ("Bachelor of Commerce (Marketing)", 20),
            ("Bachelor of Commerce (Procurement and Supply Chain Management)", 20),
            ("Bachelor of Commerce (Entrepreneurship with Int'l Business)", 18),
        ],
        "Education": [
            ("Bachelor of Construction Technology Education", 19),
            ("Bachelor of Education (Arts)", 16),
            ("Bachelor of Education (Economics)", 18),
            ("Bachelor of Education (English)", 20),
            ("Bachelor of Education (Geography)", 19),
            ("Bachelor of Education (Ghanaian Language and Culture)", 20),
            ("Bachelor of Education (History)", 19),
            ("Bachelor of Education (Religious and Moral Studies)", 19),
            ("Bachelor of Education (Accounting)", 18),
            ("Bachelor of Education (Accounting with Management)", 20),
            ("Bachelor of Education (Agriculture)", 22),
            ("Bachelor of Education (Automobile and Metal Technology)", 18),
            ("Bachelor of Education (Clothing & Textiles with Mgt in Living)", 20),
            ("Bachelor of Education (Communication Design)", 17),
            ("Bachelor of Education (Construction and Woodwork Technology)", 18),
            ("Bachelor of Education (Early Childhood Education)", 20),
            ("Bachelor of Education (Electrical and Electronic Engineering)", 19),
            ("Bachelor of Education (Food & Nutrition with Mgt in Living)", 20),
            ("Bachelor of Education (French)", 19),
            ("Bachelor of Education (Government)", 19),
            ("Bachelor of Education (Health, Physical Ed. and Recreation)", 23),
            ("Bachelor of Education (Home Economics)", 18),
            ("Bachelor of Education (Inclusive Education)", 23),
            ("Bachelor of Education (ICT)", 20),
            ("Bachelor of Education (Integrated Arts)", 19),
            ("Bachelor of Education (Junior High School Education)", 22),
            ("Bachelor of Education (Management)", 20),
            ("Bachelor of Education (Management with Accounting)", 18),
            ("Bachelor of Education (Mathematics)", 18),
            ("Bachelor of Education (Primary Education)", 21),
            ("Bachelor of Education (Psychology)", 16),
            ("Bachelor of Education (Robotics and Intelligent Systems)", 22),
            ("Bachelor of Education (Science)", 22),
            ("Bachelor of Education (Social Sciences)", 16),
            ("Bachelor of Education (Social Studies)", 18),
        ],
        "Law & Medicine": [
            ("Bachelor of Laws (LLB)", 12),
            ("Bachelor of Medicine and Bachelor of Surgery", 8),
        ],
        "Science, Agriculture & Health": [
            ("BSc. Actuarial Science", 16),
            ("BSc. Agribusiness", 20),
            ("BSc. Agricultural Engineering", 20),
            ("BSc. Agricultural Extension", 20),
            ("BSc. Agricultural Extension and Community Development", 21),
            ("BSc. Agriculture", 18),
            ("BSc. Agro Processing", 20),
            ("BSc. Biochemistry", 16),
            ("BSc. Biomedical Sciences", 16),
            ("BSc. Chemical Engineering", 18),
            ("BSc. Chemistry", 18),
            ("BSc. Computer Science", 15),
            ("BSc. Conservation Biology and Entomology", 25),
            ("BSc. Diagnostic Imaging Technology", 14),
            ("BSc. Diagnostic Medical Sonography", 14),
            ("BSc. Dietetics", 14),
            ("BSc. Dispensing Opticianry", 18),
            ("BSc. Economics", 16),
            ("BSc. Economics with Finance", 17),
            ("BSc. Engineering Physics", 18),
            ("BSc. Environmental Science", 19),
            ("BSc. Fisheries and Aquatic Sciences", 20),
            ("BSc. Food Chemistry", 16),
            ("BSc. Forensic Science", 17),
            ("BSc. Geography and Regional Planning", 17),
            ("BSc. Health Information Management", 18),
            ("BSc. Horticulture", 20),
            ("BSc. Hospitality Management", 20),
            ("BSc. Industrial Chemistry", 21),
            ("BSc. Information Technology", 15),
            ("BSc. Laboratory Technology", 18),
            ("BSc. Livestock Science and Meat Technology", 20),
            ("BSc. Mathematics", 20),
            ("BSc. Mathematics and Statistics", 17),
            ("BSc. Mathematics with Business", 22),
            ("BSc. Mathematics with Economics", 17),
            ("BSc. Medical Laboratory Science", 12),
            ("BSc. Mental Health Nursing", 12),
            ("BSc. Meteorology and Atmospheric Physics", 19),
            ("BSc. Midwifery", 12),
            ("BSc. Molecular Biology and Biotechnology", 20),
            ("BSc. Nursing", 12),
            ("BSc. Nutrition", 15),
            ("BSc. Physician Assistant Studies", 11),
            ("BSc. Physics", 22),
            ("BSc. Psychology", 20),
            ("BSc. Sport and Exercise Science", 22),
            ("BSc. Statistics", 25),
            ("BSc. Tourism Management", 22),
            ("BSc. Water and Public Health Engineering", 18),
            ("Doctor of Optometry", 12),
            ("Doctor of Pharmacy", 9),
        ],
    },

    "UDS": {
        "Health Sciences": [
            ("MBChB (Medicine)", 9),
            ("Doctor of Pharmacy", 12),
            ("Doctor of Pharmacy (Fee Paying)", 18),
            ("BSc. Nursing", 7, "7-10 depending on gender/science background"),
            ("BSc. Midwifery", 7, "7-10 depending on gender/science background"),
            ("BSc. Health Information Management", 18),
            ("Doctor of Medical Laboratory Sciences", 12),
            ("BSc. Medical Imaging Technology", 11, "11 regular, 11-15 fee-paying"),
            ("BSc. Community Nutrition", 18),
            ("BSc. Dietetics", 16),
        ],
    },

    "UENR": {
        "Engineering": [
            ("BSc. Petroleum Engineering", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Computer Engineering", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Electrical and Electronic Engineering", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Environmental Engineering", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Mechanical Engineering", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Renewable Energy Engineering", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Civil Engineering", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Agricultural Engineering", None, "Aggregate 6-36 (competitive)"),
        ],
        "Sciences": [
            ("BSc. Nursing", None, "Aggregate 6-36; entrance exam + interview"),
            ("BSc. Medical Laboratory Science", None, "Aggregate 6-36; entrance exam + interview"),
            ("BSc. Actuarial Science", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Biological Science", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Chemistry", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Information Technology", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Mathematics", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Statistics", None, "Aggregate 6-36 (competitive)"),
        ],
        "Natural Resources & Arts/Social Sciences": [
            ("BSc. Fire, Safety & Disaster Management", None, "Aggregate 6-36 (open track available)"),
            ("BSc. Hospitality Management", None, "Aggregate 6-36 (open track available)"),
            ("BSc. Natural Resources Management", None, "Aggregate 6-36 (open track available)"),
            ("BSc. Resource Enterprise and Entrepreneurship", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Economics", None, "Aggregate 6-36 (competitive)"),
        ],
        "Geosciences": [
            ("BSc. Planning and Sustainability", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Climate Change and Sustainable Development", None, "Aggregate 6-36; open track available"),
        ],
        "Agriculture & Technology": [
            ("BSc. Agriculture", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Agribusiness", None, "Aggregate 6-36 (competitive)"),
            ("BSc. Agricultural and Resource Economics", None, "Aggregate 6-36; open track available"),
        ],
    },

    "UG": {
        "Basic & Applied Sciences": [
            ("BSc. Agricultural Engineering", 15),
            ("BSc. Biomedical Engineering", 6),
            ("BSc. Computer Engineering", 7),
            ("BSc. Food Process Engineering", 12),
            ("BSc. Materials Science & Engineering", 13),
            ("BSc. Biological Sciences", 14),
            ("BSc. Psychology", 15),
            ("Doctor of Veterinary Medicine", 14),
            ("BSc. Actuarial Science", 11),
            ("BSc. Computer Science", 7),
            ("BSc. Information Technology", 10),
            ("BSc. Earth Science", 15),
            ("BSc. Physical Sciences", 24),
            ("BSc. Mathematical Sciences", 15),
            ("BSc. Agriculture", 22),
            ("BSc. Family and Consumer Sciences (Family & Child Studies)", 16),
            ("BSc. Family and Consumer Sciences (Food & Clothing)", 20),
        ],
        "Health Sciences": [
            ("Bachelor of Medicine and Bachelor of Surgery", 8),
            ("Bachelor of Dental Surgery", 10),
            ("Doctor of Pharmacy", 10),
            ("BSc. Nursing", 15),
            ("BSc. Midwifery", 15),
            ("BSc. Medical Laboratory Sciences", 12),
            ("BSc. Physiotherapy", 14),
            ("BSc. Dietetics", 14),
            ("BSc. Diagnostic Radiography", 13),
            ("BSc. Occupational Therapy", 14),
            ("BSc. Respiratory Therapy", 14),
            ("Bachelor of Public Health", 9),
        ],
        "Education": [
            ("Bachelor of Education in Social Studies", 24),
            ("Bachelor of Education in English", 24),
            ("Bachelor of Education in Mathematics", 24),
            ("Bachelor of Education in Science (Physics)", 24),
            ("Bachelor of Education in Science (Chemistry)", 24),
            ("Bachelor of Education in Science (Biology)", 24),
            ("Bachelor of Education (Early Grade Specialism)", 24),
            ("Bachelor of Education (JHS Specialism)", 24),
            ("Bachelor of Education (Upper Grade Specialism)", 24),
            ("Bachelor of Arts in Sports and Physical Culture", 24),
            ("BSc. Administration (Kumasi/Takoradi City Campuses)", 24),
            ("Bachelor of Education in French", 24),
            ("Bachelor of Education in Spanish", 24),
            ("Bachelor of Education in Performing Arts", 24),
            ("Bachelor of Education in ICT", 12),
            ("Bachelor of Education in Consumer Sciences", 20),
            ("Bachelor of Education in Arabic", 24),
            ("Bachelor of Education in Computer Science", 9),
        ],
        "Distance Education": [
            ("Bachelor of Arts (Distance)", 30),
            ("BSc. Administration (Distance)", 30),
            ("BSc. Information Technology (Distance)", 24),
            ("Bachelor of Education Early Grade (Distance)", 30),
            ("Bachelor of Education Upper Grade (Distance)", 30),
            ("Bachelor of Education JHS (Distance)", 30),
        ],
        "Humanities": [
            ("Bachelor of Laws", 7),
            ("BSc. Administration", 9),
            ("BSc. Administration (Full Fee Paying)", 12),
            ("Bachelor of Arts (General Arts Background)", 16),
            ("Bachelor of Arts (Full Fee Paying)", 20),
            ("Bachelor of Arts (Bouquets with a Business Subject)", 12),
            ("Bachelor of Arts (Business/Science/Vocational Background)", 14),
            ("Bachelor of Fine Arts", 20),
            ("Bachelor of Music", 20),
        ],
        "Accra City Campus": [
            ("Bachelor of Arts (City Campus)", 24),
            ("BSc. Administration (City Campus)", 24),
        ],
    },
}
