import django, os, sys
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()
from careers.models import LearningArea, Subject, Career, CareerRecommendationReason
from eligibility.models import University, Program
CareerRecommendationReason.objects.all().delete()
Career.objects.all().delete()
Subject.objects.all().delete()
LearningArea.objects.all().delete()
Program.objects.all().delete()
University.objects.all().delete()
la_science = LearningArea.objects.create(name="Science", school_type="SHS")
la_arts = LearningArea.objects.create(name="General Arts", school_type="SHS")
la_business = LearningArea.objects.create(name="Business", school_type="SHS")
la_apptech = LearningArea.objects.create(name="Applied Technology", school_type="SHS")
la_homeec = LearningArea.objects.create(name="Home Economics", school_type="SHS")
la_vpa = LearningArea.objects.create(name="Visual and Performing Arts", school_type="SHS")
la_agric = LearningArea.objects.create(name="Agriculture", school_type="SHS")
la_lang = LearningArea.objects.create(name="Languages", school_type="SHS")
la_global = LearningArea.objects.create(name="Global Studies", school_type="SHS")
la_eng = LearningArea.objects.create(name="Engineering", school_type="STEM")
la_bio = LearningArea.objects.create(name="Biomedical Science", school_type="STEM")
la_cs = LearningArea.objects.create(name="Computer Science", school_type="STEM")
la_it = LearningArea.objects.create(name="Information Technology", school_type="STEM")
la_robot = LearningArea.objects.create(name="Robotics", school_type="STEM")
la_avia = LearningArea.objects.create(name="Aviation and Aerospace", school_type="STEM")
la_mfg = LearningArea.objects.create(name="Manufacturing", school_type="STEM")
s_math = Subject.objects.create(name="Mathematics", group="A", is_mandatory=True)
s_eng = Subject.objects.create(name="English Language", group="A", is_mandatory=True)
s_soc = Subject.objects.create(name="Social Studies", group="A", is_mandatory=True)
s_sci = Subject.objects.create(name="General Science", group="A", is_mandatory=True)
s_bio = Subject.objects.create(name="Biology", group="B", learning_area=la_science, is_mandatory=True)
s_chem = Subject.objects.create(name="Chemistry", group="B", learning_area=la_science, is_mandatory=True)
s_phys = Subject.objects.create(name="Physics", group="B", learning_area=la_science, is_mandatory=True)
s_addmath = Subject.objects.create(name="Additional Mathematics", group="C", learning_area=la_science)
s_ict = Subject.objects.create(name="ICT", group="C", learning_area=la_science)
s_compsci = Subject.objects.create(name="Computer Science", group="C", learning_area=la_science)
s_geo = Subject.objects.create(name="Geography", group="D", learning_area=la_science)
s_econ = Subject.objects.create(name="Economics", group="D", learning_area=la_science)
s_gov = Subject.objects.create(name="Government", group="D", learning_area=la_science)
s_hist = Subject.objects.create(name="History", group="D", learning_area=la_science)
s_lit = Subject.objects.create(name="Literature in English", group="D", learning_area=la_science)
s_crs = Subject.objects.create(name="Christian Religious Studies", group="B", learning_area=la_arts)
s_music = Subject.objects.create(name="Music", group="B", learning_area=la_arts)
s_french = Subject.objects.create(name="French", group="C", learning_area=la_arts)
s_ghanlang = Subject.objects.create(name="Ghanaian Language", group="C", learning_area=la_arts)
s_bizmgt = Subject.objects.create(name="Business Management", group="B", learning_area=la_business, is_mandatory=True)
s_acct = Subject.objects.create(name="Accounting", group="B", learning_area=la_business, is_mandatory=True)
s_design_comm = Subject.objects.create(name="Design and Communication Technology", group="B", learning_area=la_apptech, is_mandatory=True)
s_agriculture = Subject.objects.create(name="Agriculture", group="B", learning_area=la_agric, is_mandatory=True)
s_mgmt_living = Subject.objects.create(name="Management in Living", group="B", learning_area=la_homeec, is_mandatory=True)
s_food_nutr = Subject.objects.create(name="Food and Nutrition", group="B", learning_area=la_homeec)
s_clothing = Subject.objects.create(name="Clothing and Textiles", group="B", learning_area=la_homeec)
s_art_design = Subject.objects.create(name="Art and Design Foundation", group="B", learning_area=la_vpa, is_mandatory=True)
s_perf_arts = Subject.objects.create(name="Performing Arts", group="B", learning_area=la_vpa)
s_engineering = Subject.objects.create(name="Engineering", group="B", learning_area=la_eng, is_mandatory=True)
s_biomedical = Subject.objects.create(name="Biomedical Science", group="B", learning_area=la_bio, is_mandatory=True)
s_comp_sci_stem = Subject.objects.create(name="Computer Science STEM", group="B", learning_area=la_cs, is_mandatory=True)
s_robotics_stem = Subject.objects.create(name="Robotics", group="B", learning_area=la_robot, is_mandatory=True)
s_info_tech = Subject.objects.create(name="Information Technology", group="B", learning_area=la_it, is_mandatory=True)
s_avia_tech = Subject.objects.create(name="Aviation Technology", group="B", learning_area=la_avia, is_mandatory=True)
s_mfg_eng = Subject.objects.create(name="Manufacturing Engineering", group="B", learning_area=la_mfg, is_mandatory=True)
core_set = [s_math, s_eng, s_soc, s_sci]
def mk(name, icon, kw, la, mand, rec, why, rr=None):
    c = Career.objects.create(name=name, icon=icon, keywords=kw, learning_area=la, why_text=why)
    for s in core_set: c.core_subjects.add(s)
    for s in mand: c.mandatory_electives.add(s)
    for s in rec: c.recommended_electives.add(s)
    if rr:
        for subj, reason in rr.items():
            CareerRecommendationReason.objects.create(career=c, subject=subj, reason=reason)
mk("Medical Doctor","stethoscope","doctor,medicine,medical,physician,surgeon,hospital,health,clinical",la_science,[s_bio,s_chem,s_phys],[s_addmath,s_ict],"Medicine requires Biology, Chemistry, and Physics. KNUST MBChB cut-off is aggregate 6.",{s_addmath:"Strengthens quantitative reasoning.",s_ict:"Digital health records are now core clinical skills."})
mk("Civil Engineer","bridge","civil,engineer,bridge,road,structural,construction,build,infrastructure",la_science,[s_phys,s_chem,s_addmath],[s_geo,s_ict],"Civil Engineering requires Physics, Chemistry, and Mathematics. KNUST cut-off is aggregate 7.",{s_addmath:"Structural calculations are core.",s_geo:"Geology underpins foundation design."})
mk("Software Developer","laptop","software,developer,programmer,coding,code,app,web,IT,tech,computer,technology",la_cs,[s_phys,s_addmath,s_compsci],[s_ict,s_bio],"Computer Science requires Additional Mathematics and Physics. KNUST cut-off is aggregate 7.",{s_addmath:"Algorithms require strong math.",s_compsci:"Direct subject for programming."})
mk("Accountant","chart","account,accountant,finance,audit,tax,banking,financial,bank",la_business,[s_bizmgt,s_acct],[s_econ,s_addmath],"Business Management and Accounting are mandatory. KNUST Accounting cut-off is aggregate 7.",{s_econ:"Economics is tested in all accounting programs.",s_addmath:"Opens doors to Finance and Actuarial Science."})
mk("Lawyer","scales","lawyer,law,legal,attorney,court,justice,llb,barrister,solicitor",la_arts,[s_econ,s_gov,s_hist],[s_lit,s_crs,s_french],"KNUST LLB cut-off is aggregate 6. UG and UCC also offer LLB.",{s_lit:"Critical reading is essential in law.",s_gov:"Constitutional law is core in LLB programs."})
mk("Nurse","hospital","nurse,nursing,midwife,midwifery,clinical,ward,patient,healthcare",la_science,[s_bio,s_chem,s_phys],[s_addmath,s_food_nutr],"Nursing requires Biology, Chemistry, and Physics. KNUST Nursing cut-off is aggregate 7.",{s_food_nutr:"Nutrition is a core clinical competency.",s_addmath:"Pharmacology calculations require strong mathematics."})
mk("Agricultural Scientist","seedling","agric,agriculture,farm,crop,soil,food,plant,agronomy,horticulture,farming,livestock",la_agric,[s_agriculture,s_chem,s_phys],[s_bio,s_addmath,s_food_nutr],"Agriculture is the mandatory elective. KNUST Agriculture cut-off is aggregate 20.",{s_bio:"Plant biology and genetics are core.",s_chem:"Soil chemistry is tested from year one."})
mk("Architect","building","architect,architecture,design,building,structure,urban,planning,interior",la_science,[s_phys,s_addmath,s_geo],[s_chem,s_art_design],"KNUST Architecture cut-off is aggregate 7.",{s_addmath:"Structural engineering calculations are core.",s_art_design:"Technical drawing is foundational."})
mk("Pharmacist","pill","pharmacy,pharmacist,drug,medicine,pharmaceutical,pharm,dispensing",la_science,[s_bio,s_chem,s_phys],[s_addmath,s_ict],"Pharm D requires Biology, Chemistry, and Physics. KNUST cut-off is aggregate 6.",{s_addmath:"Pharmaceutical calculations require advanced mathematics.",s_ict:"Digital dispensing systems are now standard."})
mk("Journalist","newspaper","journalist,journalism,media,reporter,news,broadcast,communication,press,writing",la_arts,[s_econ,s_gov,s_hist],[s_lit,s_french,s_ghanlang],"KNUST Media and Communication Studies cut-off is aggregate 9.",{s_lit:"Analytical writing is the core skill.",s_french:"French opens doors to international journalism."})
mk("Biomedical Engineer","microscope","biomedical,biomed,medical device,prosthetic,implant,biomechanics,clinical engineer",la_bio,[s_bio,s_chem,s_phys],[s_addmath,s_ict,s_compsci],"KNUST Biomedical Engineering cut-off is aggregate 6.",{s_addmath:"Biomechanics requires advanced mathematics.",s_compsci:"Medical device programming requires computer science."})
mk("Economist","chart increasing","economist,economics,economic,policy,development,research,statistics,monetary",la_arts,[s_econ,s_geo,s_gov],[s_addmath,s_hist,s_bizmgt],"KNUST BA Economics cut-off is aggregate 10.",{s_addmath:"Econometrics requires advanced mathematics.",s_hist:"Economic history is core at university level."})
knust = University.objects.create(name="Kwame Nkrumah University of Science and Technology", short_name="KNUST", location="Kumasi", website="https://www.knust.edu.gh")
ug = University.objects.create(name="University of Ghana", short_name="UG", location="Legon, Accra", website="https://www.ug.edu.gh")
ucc = University.objects.create(name="University of Cape Coast", short_name="UCC", location="Cape Coast", website="https://www.ucc.edu.gh")
uds = University.objects.create(name="University for Development Studies", short_name="UDS", location="Tamale", website="https://www.uds.edu.gh")
uenr = University.objects.create(name="University of Energy and Natural Resources", short_name="UENR", location="Sunyani", website="https://www.uenr.edu.gh")
def p(uni, name, fac, agg, la=None):
    prog = Program.objects.create(university=uni, name=name, faculty=fac, learning_area=la, aggregate=agg, year=2024)
p(knust,"BSc. Human Biology MBChB","College of Health Sciences",6,la_science)
p(knust,"BSc. Biomedical Engineering","College of Engineering",6,la_science)
p(knust,"BSc. Computer Engineering","College of Engineering",6,la_science)
p(knust,"BSc. Electrical/Electronic Engineering","College of Engineering",6,la_science)
p(knust,"Pharm D Doctor of Pharmacy","College of Health Sciences",6,la_science)
p(knust,"Bachelor of Dental Surgery","College of Health Sciences",6,la_science)
p(knust,"BSc. Petroleum Engineering","College of Engineering",6,la_science)
p(knust,"LLB Bachelor of Laws","Faculty of Law",6,la_arts)
p(knust,"BSc. Architecture","College of Art and Built Environment",7,la_science)
p(knust,"BSc. Aerospace Engineering","College of Engineering",7,la_science)
p(knust,"BSc. Chemical Engineering","College of Engineering",7,la_science)
p(knust,"BSc. Civil Engineering","College of Engineering",7,la_science)
p(knust,"BSc. Mechanical Engineering","College of Engineering",7,la_science)
p(knust,"BSc. Medical Laboratory Science","College of Health Sciences",7,la_science)
p(knust,"BSc. Nursing","College of Health Sciences",7,la_science)
p(knust,"BSc. Business Administration Accounting","KNUST School of Business",7,la_business)
p(knust,"BSc. Computer Science","College of Science",7,la_science)
p(knust,"BSc. Land Economy","College of Art and Built Environment",8,la_arts)
p(knust,"BSc. Midwifery","College of Health Sciences",8,la_science)
p(knust,"BSc. Geological Engineering","College of Engineering",8,la_science)
p(knust,"BSc. Biochemistry","College of Science",9,la_science)
p(knust,"BSc. Biological Science","College of Science",9,la_science)
p(knust,"BSc. Dietetics","College of Science",9,la_science)
p(knust,"BA. Media and Communication Studies","College of Humanities",9,la_arts)
p(knust,"BA. Political Studies","College of Humanities",9,la_arts)
p(knust,"BSc. Business Administration Marketing","KNUST School of Business",9,la_business)
p(knust,"BSc. Human Nutrition","College of Science",10,la_science)
p(knust,"BSc. Information Technology","College of Science",10,la_science)
p(knust,"BA. Economics","College of Humanities",10,la_arts)
p(knust,"BSc. Actuarial Science","College of Science",10,la_science)
p(knust,"BSc. Food Science and Technology","College of Science",11,la_science)
p(knust,"BSc. Statistics","College of Science",12,la_science)
p(knust,"BSc. Environmental Science","College of Science",12,la_science)
p(knust,"BSc. Physiotherapy and Sports Science","College of Health Sciences",12,la_science)
p(knust,"BA. English","College of Humanities",13,la_arts)
p(knust,"BSc. Chemistry","College of Science",15,la_science)
p(knust,"BSc. Mathematics","College of Science",15,la_science)
p(knust,"BSc. Physics","College of Science",16,la_science)
p(knust,"BSc. Agriculture","College of Agriculture",20,la_agric)
p(knust,"BSc. Agricultural Biotechnology","College of Agriculture",17,la_agric)
p(knust,"BSc. Agribusiness Management","College of Agriculture",15,la_agric)
p(knust,"BSc. Natural Resources Management","College of Agriculture",18,la_agric)
p(ug,"MBChB Medicine","School of Medicine",8,la_science)
p(ug,"LLB Bachelor of Laws","School of Law",12,la_arts)
p(ug,"BSc. Computer Science","College of Basic and Applied Sciences",15,la_science)
p(ug,"BSc. Information Technology","College of Basic and Applied Sciences",15,la_science)
p(ug,"BSc. Biomedical Sciences","College of Health Sciences",16,la_science)
p(ug,"BSc. Biochemistry","College of Basic and Applied Sciences",16,la_science)
p(ug,"BSc. Economics","College of Humanities",16,la_arts)
p(ug,"BSc. Actuarial Science","College of Basic and Applied Sciences",16,la_science)
p(ug,"BSc. Nursing","School of Nursing",12,la_science)
p(ug,"BSc. Midwifery","School of Nursing",12,la_science)
p(ug,"BSc. Medical Laboratory Science","College of Health Sciences",12,la_science)
p(ug,"Doctor of Pharmacy","School of Pharmacy",10,la_science)
p(ug,"BSc. Agriculture","College of Agriculture",18,la_agric)
p(ug,"BSc. Agribusiness","College of Agriculture",20,la_agric)
p(ug,"BSc. Chemical Engineering","College of Basic and Applied Sciences",18,la_science)
p(ug,"Bachelor of Commerce Accounting","Business School",15,la_business)
p(ug,"Bachelor of Commerce Finance","Business School",16,la_business)
p(ug,"BSc. Mathematics","College of Basic and Applied Sciences",20,la_science)
p(ug,"BSc. Physics","College of Basic and Applied Sciences",22,la_science)
p(ug,"Doctor of Optometry","College of Health Sciences",12,la_science)
p(ug,"BSc. Environmental Science","College of Basic and Applied Sciences",19,la_science)
p(ug,"BSc. Dietetics","College of Health Sciences",14,la_science)
p(ucc,"MBChB Medicine","School of Medicine",9,la_science)
p(ucc,"Doctor of Pharmacy","School of Pharmacy",12,la_science)
p(ucc,"BSc Nursing","School of Nursing",9,la_science)
p(ucc,"BSc Midwifery","School of Nursing",9,la_science)
p(ucc,"Doctor of Medical Laboratory Sciences","School of Allied Health",12,la_science)
p(ucc,"BSc Medical Imaging Technology","School of Allied Health",11,la_science)
p(ucc,"BSc Community Nutrition","School of Allied Health",18,la_science)
p(ucc,"BSc Dietetics","School of Allied Health",16,la_science)
p(ucc,"BSc Health Information Management","School of Public Health",18,la_science)
p(uds,"BSc. Civil Engineering","School of Engineering",6,la_science)
p(uds,"BSc. Computer Engineering","School of Engineering",6,la_science)
p(uds,"BSc. Electrical and Electronic Engineering","School of Engineering",6,la_science)
p(uds,"BSc. Mechanical Engineering","School of Engineering",6,la_science)
p(uds,"BSc. Nursing","School of Sciences",6,la_science)
p(uds,"BSc. Medical Laboratory Science","School of Sciences",6,la_science)
p(uds,"BSc. Computer Science","School of Sciences",6,la_science)
p(uds,"BSc. Agriculture","School of Agriculture",6,la_agric)
p(uds,"BSc. Economics","School of Arts and Social Sciences",6,la_arts)
p(uenr,"BSc. Biomedical Engineering","College of Basic and Applied Sciences",6,la_science)
p(uenr,"BSc. Computer Engineering","College of Basic and Applied Sciences",7,la_science)
p(uenr,"BSc. Computer Science","College of Basic and Applied Sciences",7,la_science)
p(uenr,"LLB Bachelor of Laws","College of Humanities",7,la_arts)
p(uenr,"BSc. Administration","College of Humanities",9,la_business)
p(uenr,"BSc. Agricultural Engineering","College of Basic and Applied Sciences",15,la_agric)
p(uenr,"BSc. Actuarial Science","College of Basic and Applied Sciences",11,la_science)
p(uenr,"BSc. Information Technology","College of Basic and Applied Sciences",10,la_science)
p(uenr,"BSc. Nursing","College of Health Sciences",15,la_science)
p(uenr,"BSc. Medical Laboratory Sciences","College of Health Sciences",12,la_science)
p(uenr,"Doctor of Pharmacy","College of Health Sciences",10,la_science)
p(uenr,"MBChB Medicine","College of Health Sciences",8,la_science)
p(uenr,"BSc. Agriculture","School of Agriculture",6,la_agric)
p(uenr,"BSc. Economics","School of Arts and Social Sciences",6,la_arts)
p(uenr,"BSc. Natural Resources Management","School of Natural Resources",6,la_agric)
p(uenr,"BSc. Midwifery","College of Health Sciences",15,la_science)
p(uenr,"BSc. Physiotherapy","College of Health Sciences",14,la_science)
p(uenr,"BSc. Dietetics","College of Health Sciences",14,la_science)
p(uenr,"Bachelor of Public Health","College of Health Sciences",9,la_science)
print("=== SEED COMPLETE ===")
from careers.models import LearningArea, Subject, Career
from eligibility.models import University, Program
print(f"Learning Areas: {LearningArea.objects.count()}")
print(f"Subjects: {Subject.objects.count()}")
print(f"Careers: {Career.objects.count()}")
print(f"Universities: {University.objects.count()}")
print(f"Programs: {Program.objects.count()}")
