# Generated by Django 6.0.5 on 2026-06-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='aggregate',
            field=models.IntegerField(blank=True, help_text='WASSCE aggregate cut-off (lower is better)', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='year',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
        migrations.DeleteModel(
            name='Cutoff',
        ),
    ]
