# Generated by Django 6.0.5 on 2026-06-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_career_icon'),
        ('eligibility', '0002_program_aggregate_program_year_delete_cutoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='learning_area',
        ),
        migrations.AddField(
            model_name='program',
            name='learning_areas',
            field=models.ManyToManyField(blank=True, to='careers.learningarea'),
        ),
    ]
