# Generated by Django 6.0.5 on 2026-06-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_remove_subject_group_remove_subject_is_mandatory_and_more'),
        ('eligibility', '0003_remove_program_learning_area_program_learning_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='learning_areas',
        ),
        migrations.RemoveField(
            model_name='program',
            name='required_subjects',
        ),
        migrations.CreateModel(
            name='ProgramRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective_subjects', models.ManyToManyField(blank=True, related_name='program_elective_requirements', to='careers.subject')),
                ('learning_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='careers.learningarea')),
                ('mandatory_subjects', models.ManyToManyField(blank=True, related_name='program_mandatory_requirements', to='careers.subject')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='eligibility.program')),
            ],
        ),
    ]
