# Generated by Django 6.0.5 on 2026-06-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_remove_subject_group_remove_subject_is_mandatory_and_more'),
        ('eligibility', '0005_programrequirement_core_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='core_subjects',
            field=models.ManyToManyField(blank=True, limit_choices_to={'name__in': ['Mathematics', 'English Language', 'Social Studies', 'General Science']}, related_name='programs', to='careers.subject'),
        ),
    ]
