# Generated by Django 6.0.5 on 2026-06-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0006_program_core_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programrequirement',
            name='core_subjects',
        ),
    ]
