# Generated by Django 6.0.5 on 2026-07-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0007_remove_programrequirement_core_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='campus',
            field=models.CharField(blank=True, default='Main Campus', max_length=150),
        ),
        migrations.AddField(
            model_name='program',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes or requirements for this program offering'),
        ),
    ]
