# Generated by Django 6.0.5 on 2026-08-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0008_program_campus_program_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='faculty',
            new_name='college',
        ),
    ]
