# Generated by Django 6.0.5 on 2026-08-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0009_rename_faculty_program_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='min_passing_grade',
            field=models.IntegerField(default=6, help_text='Worst acceptable WASSCE grade for this program (6=C6, 7=D7). Most programs require C6 or better.'),
        ),
        migrations.AddField(
            model_name='university',
            name='grading_scale',
            field=models.JSONField(blank=True, default=dict, help_text='Maps WASSCE numeric grades (1-9) to university-specific aggregate points. E.g. KNUST: C4,C5,C6 all count as 4.'),
        ),
    ]
