# Generated by Django 6.0.5 on 2026-09-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0010_program_min_passing_grade_university_grading_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='about',
            field=models.TextField(blank=True, help_text='Overview description of the university'),
        ),
        migrations.AddField(
            model_name='university',
            name='academic_year_start',
            field=models.CharField(blank=True, default='September 2026', help_text='e.g., September 2026', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='application_deadline',
            field=models.CharField(blank=True, default='June 2026', help_text='e.g., June 2026', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='entry_requirements',
            field=models.TextField(blank=True, help_text='General entry requirements (one per line or paragraph). Leave blank to use default WASSCE requirements.'),
        ),
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.URLField(blank=True, help_text='Hero background image URL'),
        ),
        migrations.AddField(
            model_name='university',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Campus thumbnail image URL'),
        ),
    ]
